name: break_the_bubble
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # Updated workmanager to a newer version compatible with modern Flutter.
  workmanager: ^0.9.0
  flutter_overlay_window: ^0.5.0
  shared_preferences: ^2.2.3
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
